const { loadModule, assert, equal, done } = require("./helpers")
const Demo = loadModule("Demo.js")
const Model = loadModule("Model.js")

const now = Date.UTC(2026, 8, 2, 12, 0)
const place = Demo.defaultPlace()
equal([place.stopId, place.stopName, place.walkMinutes], ["204420", "Sydenham Station", 5], "demo place")
const board = Demo.board(now)
equal(board.length, 8, "demo board has eight screenshot-ready rows")
equal(board.filter(d => d.cancelled).length, 1, "demo has one cancellation")
equal(board.filter(d => d.realtime && d.estimatedMs - d.plannedMs === 4 * 60000).length, 1, "demo has one four-minute delay")
equal(board.filter(d => !d.realtime).length, 2, "demo has two timetable-only services")
equal(Model.collectAlerts(board).length, 2, "demo has two distinct alerts")
equal(Model.collectAlerts(board).filter(a => a.disruption).length, 1, "one demo alert is a disruption")
equal(Array.from(new Set(board.map(d => d.line))).sort(), ["M1", "T4", "T8"], "demo spans T4, T8 and M1")
const projected = Model.boardFor(board, place, now)
assert(Model.buildRows(projected, place, now).length >= 4, "demo projects into departure rows")
assert(/^T4 · [0-9]+′$/.test(Model.pillText(projected, place, now)), "demo produces a pill string")
equal(Demo.locations("Wynyard")[0].id, "200080", "demo stop search")
assert(Demo.locations("Sydenham")[0].isStop, "demo search marks stops")
const journeys = Demo.journeys(now)
assert(journeys.length && journeys[0].legs.some(l => l.kind === "walk") && journeys[0].legs.some(l => l.kind === "ride"), "demo journey")
done("test_demo")
