const { loadModule, assert, equal, done } = require("./helpers")
const Demo = loadModule("Demo.js")
const Model = loadModule("Model.js")

const now = Date.UTC(2026, 8, 2, 12, 0)
const place = Demo.defaultPlace()
equal([place.stopId, place.stopName, place.walkMinutes], ["204420", "Sydenham Station", 5], "demo place")
const board = Demo.board(now)
assert(board.length >= 5, "demo board has useful rows")
assert(board.some(d => d.cancelled), "demo has a cancellation")
assert(board.some(d => d.realtime && d.estimatedMs > d.plannedMs), "demo has a delay")
assert(board.some(d => !d.realtime), "demo has a timetable-only service")
assert(board.some(d => d.infos.length), "demo has an alert")
const projected = Model.boardFor(board, place, now)
assert(Model.buildRows(projected, place, now).length >= 4, "demo projects into departure rows")
assert(/^T4 · [0-9]+′$/.test(Model.pillText(projected, place, now)), "demo produces a pill string")
equal(Demo.locations("Wynyard")[0].id, "200080", "demo stop search")
assert(Demo.locations("Sydenham")[0].isStop, "demo search marks stops")
const journeys = Demo.journeys(now)
assert(journeys.length && journeys[0].legs.some(l => l.kind === "walk") && journeys[0].legs.some(l => l.kind === "ride"), "demo journey")
done("test_demo")
